services:
  supplier:
    build: .
    environment:
      - ENTITY=supplier
    container_name: sdt2-supplier

  warehouse:
    build: .
    environment:
      - ENTITY=warehouse
    ports:
      - 6000:6000
    depends_on:
      - supplier
    container_name: sdt2-warehouse
  
  factory1:
    build: .
    environment:
      - ENTITY=factory1
    ports:
      - 6001:6000
    depends_on:
      - warehouse
    container_name: sdt2-factory1

  store:
    build: .
    environment:
      - ENTITY=store
    ports:
      - 6003:6000
    depends_on:
      - factory1
    container_name: sdt2-store
